CREATE TYPE "credit_role" AS ENUM (
  'director',
  'writer',
  'actor'
);

CREATE TABLE "movies" (
  "movie_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "imdb_id" varchar(12) UNIQUE NOT NULL,
  "title" varchar(300) NOT NULL,
  "release_date" date,
  "runtime_min" integer,
  "plot" text,
  "poster_url" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "genres" (
  "genre_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "movie_genres" (
  "movie_id" integer NOT NULL,
  "genre_id" integer NOT NULL,
  PRIMARY KEY ("movie_id", "genre_id")
);

CREATE TABLE "people" (
  "person_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "imdb_person_id" varchar(12) UNIQUE,
  "full_name" varchar(200) NOT NULL,
  "birth_year" integer
);

CREATE TABLE "movie_credits" (
  "credit_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movie_id" integer NOT NULL,
  "person_id" integer NOT NULL,
  "role" credit_role NOT NULL,
  "character_name" varchar(200),
  "billing_order" integer
);

CREATE TABLE "rating_sources" (
  "source_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "scale_max" numeric(5,1) NOT NULL
);

CREATE TABLE "external_ratings" (
  "movie_id" integer NOT NULL,
  "source_id" integer NOT NULL,
  "score" numeric(5,1) NOT NULL,
  "vote_count" integer,
  "retrieved_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("movie_id", "source_id")
);

CREATE TABLE "users" (
  "user_id" uuid PRIMARY KEY,
  "username" varchar(30) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "reviews" (
  "review_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "movie_id" integer NOT NULL,
  "stars" smallint NOT NULL,
  "body" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE INDEX ON "movies" ("title");

CREATE INDEX ON "movies" ("release_date");

CREATE INDEX ON "movie_credits" ("movie_id");

CREATE INDEX ON "movie_credits" ("person_id");

CREATE UNIQUE INDEX ON "reviews" ("user_id", "movie_id");

CREATE INDEX ON "reviews" ("movie_id");

COMMENT ON COLUMN "movies"."imdb_id" IS 'e.g. tt0111161';

COMMENT ON COLUMN "movies"."runtime_min" IS 'CHECK runtime_min > 0';

COMMENT ON COLUMN "people"."imdb_person_id" IS 'e.g. nm0000151';

COMMENT ON COLUMN "movie_credits"."character_name" IS 'Only for actors';

COMMENT ON COLUMN "rating_sources"."name" IS 'IMDb, Rotten Tomatoes';

COMMENT ON COLUMN "rating_sources"."scale_max" IS '10 for IMDb, 100 for RT';

COMMENT ON COLUMN "users"."user_id" IS 'Matches Supabase auth.users id';

COMMENT ON COLUMN "reviews"."stars" IS 'CHECK stars BETWEEN 1 AND 10';

ALTER TABLE "movie_genres" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("movie_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movie_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("genre_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movie_credits" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("movie_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movie_credits" ADD FOREIGN KEY ("person_id") REFERENCES "people" ("person_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "external_ratings" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("movie_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "external_ratings" ADD FOREIGN KEY ("source_id") REFERENCES "rating_sources" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("movie_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
